"""Multi-Format Report Export Module for YouTube Intelligence Studio.

Converts Markdown intelligence reports into:
1. Styled HTML documents (.html)
2. Microsoft Word documents (.docx)
3. Google Docs paste-ready formatted payloads
"""

import io
import re
import markdown
from typing import Optional
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH


def markdown_to_styled_html(md_text: str, title: str = "YouTube Intelligence Report") -> str:
    """Convert Markdown to a standalone, beautifully styled HTML document.

    Args:
        md_text: Raw Markdown report content.
        title: HTML document title.

    Returns:
        Complete HTML document string with modern embedded CSS styling.
    """
    html_body = markdown.markdown(
        md_text,
        extensions=["extra", "codehilite", "toc", "tables"]
    )

    styled_html = f"""<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            line-height: 1.7;
            color: #24292f;
            background-color: #f6f8fa;
            padding: 40px 20px;
            margin: 0;
        }}
        .container {{
            max-width: 900px;
            margin: 0 auto;
            background: #ffffff;
            padding: 48px;
            border-radius: 12px;
            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.08);
            border: 1px solid #d0d7de;
        }}
        h1 {{
            font-size: 2.2em;
            border-bottom: 2px solid #eaecef;
            padding-bottom: 0.3em;
            color: #0969da;
            margin-top: 0;
        }}
        h2 {{
            font-size: 1.6em;
            border-bottom: 1px solid #eaecef;
            padding-bottom: 0.3em;
            color: #1f2328;
            margin-top: 24px;
        }}
        h3 {{
            font-size: 1.25em;
            color: #24292f;
            margin-top: 20px;
        }}
        blockquote {{
            border-left: 4px solid #0969da;
            color: #57606a;
            padding: 8px 16px;
            margin: 16px 0;
            background-color: #f6f8fa;
            border-radius: 0 6px 6px 0;
        }}
        code {{
            background-color: #eff1f3;
            padding: 0.2em 0.4em;
            border-radius: 4px;
            font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace;
            font-size: 85%;
        }}
        ul, ol {{
            padding-left: 2em;
            margin: 12px 0;
        }}
        li {{
            margin-bottom: 6px;
        }}
        hr {{
            height: 1px;
            background-color: #d0d7de;
            border: none;
            margin: 24px 0;
        }}
        a {{
            color: #0969da;
            text-decoration: none;
        }}
        a:hover {{
            text-decoration: underline;
        }}
        .footer {{
            margin-top: 40px;
            text-align: center;
            font-size: 0.85em;
            color: #6e7781;
        }}
    </style>
</head>
<body>
    <div class="container">
        {html_body}
        <div class="footer">
            Generated by <strong>YouTube Intelligence Studio</strong>
        </div>
    </div>
</body>
</html>"""
    return styled_html


def markdown_to_docx(md_text: str, title: str = "YouTube Intelligence Report") -> io.BytesIO:
    """Convert Markdown report into formatted Microsoft Word (.docx) document bytes.

    Args:
        md_text: Raw Markdown report content.
        title: Document title.

    Returns:
        BytesIO buffer containing valid .docx file bytes.
    """
    doc = Document()

    # Document Title
    title_p = doc.add_heading(level=0)
    title_run = title_p.add_run(title)
    title_run.font.color.rgb = RGBColor(9, 105, 218)
    title_run.font.size = Pt(22)
    title_run.bold = True

    lines = md_text.splitlines()

    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue

        # Header 1
        if stripped.startswith("# "):
            h = doc.add_heading(level=1)
            r = h.add_run(stripped[2:])
            r.font.color.rgb = RGBColor(31, 35, 40)
            r.font.size = Pt(16)
            r.bold = True
        # Header 2
        elif stripped.startswith("## "):
            h = doc.add_heading(level=2)
            r = h.add_run(stripped[3:])
            r.font.color.rgb = RGBColor(31, 35, 40)
            r.font.size = Pt(14)
            r.bold = True
        # Header 3
        elif stripped.startswith("### "):
            h = doc.add_heading(level=3)
            r = h.add_run(stripped[4:])
            r.font.color.rgb = RGBColor(36, 41, 47)
            r.font.size = Pt(12)
            r.bold = True
        # Bullet list item
        elif stripped.startswith("- ") or stripped.startswith("* ") or stripped.startswith("• "):
            bullet_text = re.sub(r"^[-*•]\s+", "", stripped)
            p = doc.add_paragraph(style='List Bullet')
            # Simple bold formatting parser
            parts = re.split(r"(\*\*.*?\*\*)", bullet_text)
            for part in parts:
                if part.startswith("**") and part.endswith("**"):
                    r = p.add_run(part[2:-2])
                    r.bold = True
                else:
                    p.add_run(part)
        # Numbered list item
        elif re.match(r"^\d+\.\s+", stripped):
            num_text = re.sub(r"^\d+\.\s+", "", stripped)
            p = doc.add_paragraph(style='List Number')
            parts = re.split(r"(\*\*.*?\*\*)", num_text)
            for part in parts:
                if part.startswith("**") and part.endswith("**"):
                    r = p.add_run(part[2:-2])
                    r.bold = True
                else:
                    p.add_run(part)
        # Blockquote
        elif stripped.startswith("> "):
            quote_text = stripped[2:].strip().strip('"')
            p = doc.add_paragraph()
            p.paragraph_format.left_indent = Inches(0.4)
            r = p.add_run(f'"{quote_text}"')
            r.italic = True
            r.font.color.rgb = RGBColor(87, 96, 106)
        # Horizontal Rule
        elif stripped == "---":
            p = doc.add_paragraph()
            r = p.add_run("―" * 40)
            r.font.color.rgb = RGBColor(208, 215, 222)
        # Regular Paragraph
        else:
            p = doc.add_paragraph()
            parts = re.split(r"(\*\*.*?\*\*)", stripped)
            for part in parts:
                if part.startswith("**") and part.endswith("**"):
                    r = p.add_run(part[2:-2])
                    r.bold = True
                else:
                    p.add_run(part)

    # Save to in-memory bytes buffer
    docx_io = io.BytesIO()
    doc.save(docx_io)
    docx_io.seek(0)
    return docx_io


def launch_google_docs_autopaste(report_text: str) -> None:
    """Launch Google Docs in default browser and automatically paste report content via OS robot.

    Saves report into a temporary file, invokes autopaste_docs.ps1 which sets the clipboard,
    launches https://docs.new, waits for the canvas editor to initialize, and sends Ctrl+V.
    """
    import os
    import tempfile
    import threading
    import subprocess

    def _worker():
        # Write text to temporary utf-8 file to prevent command line escaping bugs
        with tempfile.NamedTemporaryFile("w", encoding="utf-8", delete=False, suffix=".txt") as tf:
            tf.write(report_text)
            temp_path = tf.name

        script_dir = os.path.dirname(__file__)
        if os.name != "nt":
            # On Linux / Cloud container environments, open docs.new directly
            import webbrowser
            try:
                webbrowser.open_new_tab("https://docs.new")
            except Exception:
                pass
            return

        ps_script_path = os.path.join(script_dir, "autopaste_docs.ps1")
        try:
            subprocess.run(
                [
                    "powershell", "-NoProfile", "-ExecutionPolicy", "Bypass",
                    "-WindowStyle", "Hidden",
                    "-File", ps_script_path,
                    "-FilePath", temp_path
                ],
                capture_output=True,
                check=False
            )
        finally:
            try:
                os.remove(temp_path)
            except OSError:
                pass

    threading.Thread(target=_worker, daemon=True).start()


